### Get all games
GET localhost:18081/games/

### Add a game
POST localhost:18081/games/
Content-Type: application/json

{
  "name": "Crash Bandicoot",
  "description": "Lorem Ipsum about Crash",
  "numberOfPlayers": 1,
  "price": 10.99,
  "systemId": 6,
  "releaseDate": "2017-01-01"
}

### Add an invalid game (missing name)
POST localhost:18081/games/
Content-Type: application/json

{
  "description": "Lorem Ipsum about Crash",
  "systemId": 1,
  "releaseDate": "2017-01-01"
}

### Retrieve a game
GET localhost:18081/games/1

### Delete a game
DELETE localhost:18081/games/1