### Get all systems
GET localhost:18080/systems/

### Add a system
POST localhost:18080/systems/
Content-Type: application/json

{
  "name": "Playstation",
  "releaseDate": "2012-01-20"
}

### Try to add an invalid system (missing name)
POST localhost:18080/systems/
Content-Type: application/json

{
  "releaseDate": "2012-01-20"
}

### Retrieve a system
GET localhost:18080/systems/2

### Delete a system
DELETE localhost:18080/systems/1