spring:
  application:
    name: notifications
  datasource:
    password: notifications
    username: notifications
    url: jdbc:postgresql://localhost:5432/notifications
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    streams:
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      replication-factor: 1 # Default is -1 but using this stack you get an error that it doesn't support -1
      state-dir: ${java.io.tmpdir}kafka-streams${file.separator}${server.port} # A;;pw running multiple instances